CREATE TABLE ShoppingCartItem (
    [Id]      INT IDENTITY (1, 1) NOT NULL,
    UserId INT NOT NULL,
    ShoppingCartId INT NOT NULL,
    ProductId INT NOT NULL,
    ProductTicketCategoryMapId INT NOT NULL,
    Quantity INT NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    TotalPrice DECIMAL(10, 2),
    [CreatedBy]       INT            NULL,
    [CreatedDateTime] DATETIME       NULL,
    [UpdatedBy]       INT            NULL,
    [UpdatedDateTime] DATETIME       NULL,
    CONSTRAINT [FK_ShoppingCartItem_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([Id]) ,
    CONSTRAINT [FK_ShoppingCartItem_ShoppingCartId] FOREIGN KEY ([ShoppingCartId]) REFERENCES [dbo].[ShoppingCart] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_ShoppingCartItem_ProductId] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Product] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_ShoppingCartItem_ProductTicketCategoryMapId] FOREIGN KEY ([ProductTicketCategoryMapId]) REFERENCES [dbo].[ProductTicketCategoryMap] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_ShoppingCartItem_CreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_ShoppingCartItem_UpdatedBy] FOREIGN KEY ([UpdatedBy]) REFERENCES [dbo].[User] ([Id]), 
    CONSTRAINT [PK_ShoppingCartItem] PRIMARY KEY ([Id])
);
